spring.application.name=DatabaseInitApplication
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/database_init
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.clean-disabled=false
app.allowed-origins="localhost:3000"